version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROSWSER_TIMEOUT: 3800
      GRID_TIMEOUT: 3000
  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shn:/dev/shn
    ports:
      - "5881:3980"
    links:
      - hub
  firefox:
    image: selenium/node-firefox:3.141.59
    container_name: firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shn:/dev/shn
    ports:
      - "5882:3981"
    links:
      - hub